spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
#        server-addr: www.qinpiyi.com:8848
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8001   # Sentinel控制台地址
      # 规则持久化改造
      datasource:
        # 名称随意
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow   # 流控规则
        degrade:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade    # 降级规则
        system:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system   # 系统规则
        authority:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority    # 授权规则
        param-flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow   # 热点规则
  application:
    name: content-center
  profiles:
    active: dev   # 配置默认环境变量

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.dmcq.contentcenter.configuration.ribbon.rule.NacosSameClusterWeightedRule # 负载均衡规则
ribbon:
  eager-load:   # 饥饿加载，解决默认懒加载导致的首次访问过慢的问题
    clients: user-center    # 多个服务以逗号分隔
feign:
  httpclient:
    enabled: true
    max-connections: 200    #feign最大连接数
    max-connections-per-route: 50   #feign单个路径最大连接数
  sentinel:
    enabled: true

# Actuator 健康检查配置
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:   # 描述信息
  app-name: content-center
  discription: 内容中心
  athor: qinpiyi
  email: qinpiyi@126.com




